id: A796FAA67
title: Thirty-Seven Point Maṇḍala Offering
type: translation
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:44:14.763435
  last_modified_at: 2022-02-28 22:44:14.763441
