id: A796FAA67
title: Short Maṇḍala Offering
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:44:14.760588
  last_modified_at: 2022-02-28 22:44:14.760595
