id: A796FAA67
title: 'The Method of Accomplishment of Ārya Avalokiteśvara: The Practice of Great
  Compassion & Mahāmudrā in Union'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:44:14.761921
  last_modified_at: 2022-02-28 22:44:14.761926
