id: A796FAA67
title: Töpa Gyatsoma Offering Prayer
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:44:14.764963
  last_modified_at: 2022-02-28 22:44:14.764969
