id: A796FAA67
title: Dhāraṇī of Goddess Parṇaśavarī
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 22:44:14.758625
  last_modified_at: 2022-02-28 22:44:14.758634
